version: '3.7'

services:
  flask:
    build: .
    command: >
      sh -c "flask run --host 0.0.0.0"
    container_name: flask_neuronet
    environment:
      - YANDEX_API_KEY=$YANDEX_API_KEY
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    expose:
      - 5000
